#!/usr/bin/bash

set -euo pipefail

echo "Checkingout master.."
git checkout master

echo "-----1"
git pull

echo "-----2"
git status

version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

echo "${version}"

versionWithoutSnapshot=${version//"-SNAPSHOT"/}

echo "${versionWithoutSnapshot}"

build=$(mvn -q -Dexec.executable=echo -Dexec.args='target/${project.artifactId}-VERSION.${project.packaging}' --non-recursive exec:exec)

build=${build//VERSION/$versionWithoutSnapshot}
echo "Build to generate: ${build}"

echo "Creating build.."
mvn -B release:clean && mvn -B release:prepare && mvn -B release:perform

echo "-----3"
git status

echo "-----4"
git pull

echo "-----5"
git status


echo "Calling terraform.."
terraform init && terraform apply -auto-approve -var "build=${build}"