#!/usr/bin/bash

set -euo pipefail

echo "Releasing build.."
git status
mvn -B release:prepare && mvn -B release:perform

build=$(mvn -q -Dexec.executable=echo -Dexec.args='target/${project.artifactId}-${project.version}.${project.packaging}' --non-recursive exec:exec)
echo "Generated build: ${build}"

echo "Calling terraform.."
terraform init && terraform apply -auto-approve -var "build=${build}"